import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <div className="bg-gray-100 min-h-screen">
      <header className="bg-white shadow-md py-4 px-6 sm:px-8 flex flex-col sm:flex-row justify-between items-center">
        {/* Title */}
        <h1 className="text-3xl font-bold text-gray-800 mb-4 sm:mb-0">
          <span className="text-blue-500">Find</span> Jobs
        </h1>

        {/* Navigation */}
        <nav className="flex space-x-6 text-sm font-medium">
          <a
            href="#"
            className="text-gray-600 hover:text-blue-500 transition duration-150"
          >
            Company Reviews
          </a>
          <a
            href="#"
            className="text-gray-600 hover:text-blue-500 transition duration-150"
          >
            Find Resumes
          </a>
        </nav>
      </header>

      {children}
    </div>
  );
}
