import { ExtendedJob } from "./types";

type Category = {
    name: string;
    iconColor: string;
};

export const categories: Category[] = [
    { name: 'Engineering', iconColor: 'text-green-500' },
    { name: 'Design', iconColor: 'text-yellow-500' },
    { name: 'Product', iconColor: 'text-red-500' },
    { name: 'Plumbing', iconColor: 'text-blue-500' },
    { name: 'Electrical', iconColor: 'text-orange-500' },
    { name: 'Carpentry', iconColor: 'text-brown-500' },
    { name: 'Masonry', iconColor: 'text-gray-700' },
    { name: 'Roofing', iconColor: 'text-indigo-500' },
    { name: 'Landscaping', iconColor: 'text-green-700' },
    { name: 'Painting', iconColor: 'text-purple-500' },
    { name: 'HVAC', iconColor: 'text-teal-500' },
    { name: 'Welding', iconColor: 'text-red-600' },
    { name: 'Tiling', iconColor: 'text-cyan-500' },
    { name: 'Flooring', iconColor: 'text-amber-500' },
    { name: 'Glazing', iconColor: 'text-blue-300' },
    { name: 'Drywall', iconColor: 'text-gray-400' },
    { name: 'Insulation', iconColor: 'text-yellow-600' },
    { name: 'Demolition', iconColor: 'text-red-700' },
    { name: 'Scaffolding', iconColor: 'text-gray-600' },
    { name: 'Bricklaying', iconColor: 'text-red-800' },
    { name: 'Stonework', iconColor: 'text-gray-500' },
    { name: 'Plastering', iconColor: 'text-pink-500' },
    { name: 'Paving', iconColor: 'text-brown-600' },
    { name: 'Joinery', iconColor: 'text-blue-700' },
    { name: 'Metalwork', iconColor: 'text-gray-900' },
    { name: 'Security Systems', iconColor: 'text-blue-900' },
    { name: 'Solar Installation', iconColor: 'text-yellow-400' },
    { name: 'Window Installation', iconColor: 'text-cyan-600' },
    { name: 'Fencing', iconColor: 'text-green-600' },
    { name: 'Decking', iconColor: 'text-teal-700' },
    { name: 'Garage Doors', iconColor: 'text-orange-700' },
    { name: 'Siding Installation', iconColor: 'text-purple-700' },
    { name: 'Waterproofing', iconColor: 'text-blue-800' },
    { name: 'Tree Surgery', iconColor: 'text-green-800' },
    { name: 'Asphalt Laying', iconColor: 'text-black' },
    { name: 'Drainage Systems', iconColor: 'text-blue-600' },
    { name: 'Lighting Installation', iconColor: 'text-yellow-300' },
    { name: 'Excavation', iconColor: 'text-gray-800' },
    { name: 'Heating', iconColor: 'text-red-500' },
    { name: 'Cooling', iconColor: 'text-blue-500' },
    { name: 'Cabinetry', iconColor: 'text-brown-400' },
    { name: 'Concrete Work', iconColor: 'text-gray-600' },
    { name: 'Ceiling Installation', iconColor: 'text-blue-200' },
    { name: 'Stucco Work', iconColor: 'text-gray-200' },
    { name: 'Guttering', iconColor: 'text-teal-400' },
    { name: 'Window Cleaning', iconColor: 'text-sky-400' },
    { name: 'Chimney Work', iconColor: 'text-gray-700' },
    { name: 'Bathroom Renovation', iconColor: 'text-indigo-600' },
    { name: 'Kitchen Renovation', iconColor: 'text-red-400' },
    { name: 'Driveway Installation', iconColor: 'text-gray-800' },
    { name: 'Deck Repair', iconColor: 'text-teal-600' },
    { name: 'Pool Installation', iconColor: 'text-blue-500' },
    { name: 'Sprinkler Systems', iconColor: 'text-green-500' },
    { name: 'Home Automation', iconColor: 'text-purple-400' },
    { name: 'Emergency Repairs', iconColor: 'text-red-900' },
    { name: 'Soundproofing', iconColor: 'text-gray-300' },
    { name: 'Shelving Installation', iconColor: 'text-brown-700' },
    { name: 'Water Filtration', iconColor: 'text-blue-600' },
    { name: 'Rainwater Harvesting', iconColor: 'text-green-400' },
    { name: 'Custom Furniture', iconColor: 'text-brown-300' },
    { name: 'Irrigation Systems', iconColor: 'text-green-600' },
    { name: 'Fireplace Installation', iconColor: 'text-red-600' },
    { name: 'Outdoor Kitchens', iconColor: 'text-orange-500' },
    { name: 'Patio Installation', iconColor: 'text-gray-500' },
    { name: 'Gazebo Construction', iconColor: 'text-teal-800' },
    { name: 'Greenhouse Construction', iconColor: 'text-green-500' },
    { name: 'Pond Installation', iconColor: 'text-blue-400' },
    { name: 'Fence Repair', iconColor: 'text-green-500' },
    { name: 'Pet Doors', iconColor: 'text-orange-400' },
    { name: 'Snow Removal', iconColor: 'text-blue-100' },
];


export const jobs: ExtendedJob[] = [];
